timeout: 1200s  # 20 minutes
steps:
# Install dependencies, with caching
- name: 'python:3.12-slim'
  id: "Install Dependencies"
  entrypoint: 'bash'
  args: ['-c', 'python -m pip install -r requirements.txt -r requirements-dev.txt']

# Lint the code
- name: 'python:3.12-slim'
  id: "Lint"
  entrypoint: 'bash'
  args: ['-c', 'python -m pip install ruff==0.13.3 && python -m ruff check . --fix --exclude archive/']

# Apply formatting fixes
- name: 'python:3.12-slim'
  id: "Apply Formatting"
  entrypoint: 'bash'
  args: ['-c', 'python -m pip install ruff==0.13.3 && python -m ruff format . --exclude archive/']

# Check formatting
- name: 'python:3.12-slim'
  id: "Format Check"
  entrypoint: 'bash'
  args: ['-c', 'python -m pip install ruff==0.13.3 && python -m ruff format . --check --exclude archive/']

# Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args: ['build', '-t', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:${_TAG}', '.']

# Push the Docker image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args: ['push', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:${_TAG}']

# Deploy to Cloud Run, now private and secure
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: Deploy
  entrypoint: 'gcloud'
  args:
    - 'run'
    - 'deploy'
    - '${_SERVICE_NAME}'
    - '--image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:${_TAG}'
    - '--region=${_REGION}'
    - '--platform=managed'
    - '--no-allow-unauthenticated'
    - '--service-account=${_SERVICE_ACCOUNT_EMAIL}'
    - '--update-env-vars=PROJECT_ID=${PROJECT_ID},LOCATION=${_REGION},BUCKET_NAME=${_BUCKET_NAME},TASK_QUEUE=${_TASK_QUEUE},TASK_OIDC_SA_EMAIL=${_SERVICE_ACCOUNT_EMAIL},REQUIRE_AUTH=true,FIRESTORE_COLLECTION=races'
    - '--quiet'

images:
- '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:${_TAG}'

substitutions:
  _SERVICE_NAME: 'hippique-orchestrator'
  _REPO_NAME: 'hippique-orchestrator'
  _REGION: 'europe-west1'
  _TASK_QUEUE: 'hippique-tasks-queue'
  _SERVICE_ACCOUNT_EMAIL: 'hippique-orchestrator@analyse-hippique.iam.gserviceaccount.com'
  _BUCKET_NAME: 'hippique-data-prod'
  _TAG: 'manual' # Default tag for manual builds
