steps:
# Lint, Test and Check syntax
- name: 'python:3.12-slim'
  id: "Lint and Test"
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      pip install -r requirements.txt -r requirements-dev.txt
      ruff check .
      pytest

# Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      docker build -t "${_REGION}-docker.pkg.dev/analyse-hippique/${_REPO}/${_IMAGE}:${SHORT_SHA:-manual}" .

# Push the Docker image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      docker push "${_REGION}-docker.pkg.dev/analyse-hippique/${_REPO}/${_IMAGE}:${SHORT_SHA:-manual}"

# Deploy to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: Deploy
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud run deploy hippique-analyse-0925 \
        --image="${_REGION}-docker.pkg.dev/analyse-hippique/${_REPO}/${_IMAGE}:${SHORT_SHA:-manual}" \
        --region="${_REGION}" \
        --platform=managed \
        --set-env-vars="TZ=Europe/Paris,PROJECT_ID=${_PROJECT_ID},REGION=${_REGION},SERVICE_NAME=hippique-analyse-0925,QUEUE_ID=hippique-tasks,SERVICE_ACCOUNT_EMAIL=${_SERVICE_ACCOUNT_EMAIL},GCS_BUCKET=analyse-hippique-data,REQUIRE_AUTH=true,OIDC_AUDIENCE=${_ACTUAL_CLOUD_RUN_URL},CLOUD_RUN_URL=${_ACTUAL_CLOUD_RUN_URL},USE_FIRESTORE=true,BUDGET_TOTAL=5,USE_GCS=true" \
        --quiet


substitutions:
  _PROJECT_ID: $PROJECT_ID
  _REGION: europe-west1
  _SERVICE: hippique-analyse-0925
  _REPO: hippique-orchestrator
  _IMAGE: hippique-orchestrator
  _SERVICE_ACCOUNT_EMAIL: 'sa-hippique-orchestrator@analyse-hippique.iam.gserviceaccount.com'
  _ACTUAL_CLOUD_RUN_URL: 'https://hippique-orchestrator-1084663881709.europe-west1.run.app'
