steps:
# Lint, Test and Check syntax
- name: 'python:3.12-slim'
  id: "Lint and Test"
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      pip install -r requirements.txt -r requirements-dev.txt
      ruff check .
      pytest

# Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      docker build -t "${_REGION}-docker.pkg.dev/analyse-hippique/${_REPO}/${_IMAGE}:${SHORT_SHA:-manual}" .

# Push the Docker image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      docker push "${_REGION}-docker.pkg.dev/analyse-hippique/${_REPO}/${_IMAGE}:${SHORT_SHA:-manual}"

# Deploy to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: Deploy
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud run deploy hippique-orchestrator \
        --image="${_REGION}-docker.pkg.dev/analyse-hippique/${_REPO}/${_IMAGE}:${SHORT_SHA:-manual}" \
        --region="${_REGION}" \
        --platform=managed \
        --allow-unauthenticated \
        --update-env-vars=TZ=Europe/Paris \
        --update-env-vars=PROJECT_ID=${_PROJECT_ID} \
        --update-env-vars=REGION=${_REGION} \
        --update-env-vars=SERVICE_NAME=hippique-orchestrator \
        --update-env-vars=QUEUE_ID=hippique-tasks \
        --update-env-vars=SERVICE_ACCOUNT_EMAIL=${_SERVICE_ACCOUNT_EMAIL} \
        --update-env-vars=OIDC_AUDIENCE=${_ACTUAL_CLOUD_RUN_URL} \
        --update-env-vars=CLOUD_RUN_URL=${_ACTUAL_CLOUD_RUN_URL} \
        --update-env-vars=BUDGET_TOTAL=5 \
        --quiet

# Explicitly make the service public
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: Make-Public
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud run services add-iam-policy-binding hippique-orchestrator \
        --member="allUsers" \
        --role="roles/run.invoker" \
        --region="${_REGION}" \
        --quiet

substitutions:
  _PROJECT_ID: analyse-hippique
  _REGION: europe-west1

  _REPO: hippique-orchestrator
  _IMAGE: hippique-orchestrator
  _SERVICE_ACCOUNT_EMAIL: 'sa-hippique-orchestrator@analyse-hippique.iam.gserviceaccount.com'
  _ACTUAL_CLOUD_RUN_URL: 'https://hippique-orchestrator-h3tdqmb7jq-ew.a.run.app'
