steps:
# Lint the code
- name: 'python:3.12-slim'
  id: Lint
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    pip install -r requirements-dev.txt
    ruff check .

# Install dependencies, check syntax, and run tests
- name: 'python:3.12-slim'
  id: Test
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    apt-get update && apt-get install -y curl
    pip install -r requirements.txt -r requirements-dev.txt
    pip install .
    export PYTHONPATH=$$PYTHONPATH:/workspace
    export PROJECT_ID=analyse-hippique
    export CLOUD_TASKS_SA_EMAIL=test-sa@analyse-hippique.iam.gserviceaccount.com
    export REQUIRE_AUTH=false
    echo "--- Checking Python syntax ---"
    python -m py_compile hippique_orchestrator/pipeline_run.py hippique_orchestrator/service.py
    echo "--- Debugging Calibration and Config Files ---"
    echo "Contents of calibration/:"
    ls -la calibration/ || true
    echo "Contents of config/:"
    ls -la config/ || true
    echo "Content of calibration/probabilities.yaml (if exists):"
    cat calibration/probabilities.yaml || echo "File not found"
    echo "Content of config/payout_calibration.yaml (if exists):"
    cat config/payout_calibration.yaml || echo "File not found"
    echo "--- Running smoke tests with full tracebacks ---"
    pytest -m unit -q --tb=long

# Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args: ['build', '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:$SHORT_SHA', '.']

# Push the Docker image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:$SHORT_SHA']

# Deploy to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: Deploy
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - '${_SERVICE}'
  - '--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:$SHORT_SHA'
  - '--region=${_REGION}'
  - '--platform=managed'
  - '--set-env-vars=TZ=Europe/Paris,PROJECT_ID=$PROJECT_ID,REGION=${_REGION},SERVICE_NAME=${_SERVICE},QUEUE_ID=hippique-tasks,SERVICE_ACCOUNT_EMAIL=${_SERVICE_ACCOUNT_EMAIL},GCS_BUCKET=${_SERVICE}-bucket,REQUIRE_AUTH=true,OIDC_AUDIENCE=${_ACTUAL_CLOUD_RUN_URL},USE_FIRESTORE=true,BUDGET_TOTAL=5'
  - '--quiet'

substitutions:
  _REGION: europe-west1
  _SERVICE: hippique-orchestrator
  _REPO: hippique-orchestrator
  _IMAGE: hippique-orchestrator
  _SERVICE_ACCOUNT_EMAIL: 'sa-hippique-orchestrator@analyse-hippique.iam.gserviceaccount.com'
  _ACTUAL_CLOUD_RUN_URL: 'https://hippique-orchestrator-1084663881709.europe-west1.run.app'
# Ce commentaire a été ajouté pour déclencher un nouveau build Cloud Build.