name: GPI v5.1 – H-30 / H-5

on:
  workflow_dispatch:
    inputs:
      meeting: { description: "Réunion ex: R1", required: false }
      race:    { description: "Course ex: C5", required: false }
  schedule:
    # Paris (été) : 16:25 ≈ H-30 ; 16:55 ≈ H-5  (adapte si besoin)
    - cron: "25 15 * * *"
    - cron: "55 15 * * *"

env:
  TZ: Europe/Paris
  PYTHONUTF8: "1"
  # Paramètres GPI v5.1
  GPI_BUDGET: "5"
  SP_RATIO: "0.6"
  COMBO_RATIO: "0.4"
  EV_MIN_SP: "0.20"
  EV_MIN_GLOBAL: "0.40"
  ROI_MIN_GLOBAL: "0.40"
  MAX_VOL_PER_HORSE: "0.60"
  ALLOW_JE_NA: "false"

jobs:
  gpi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt || true
          pip install requests beautifulsoup4 pyyaml python-dotenv pytest

      - name: Resolve inputs
        id: in
        run: |
          echo "MEETING=${{ github.event.inputs.meeting || '' }}" >> $GITHUB_OUTPUT
          echo "RACE=${{ github.event.inputs.race || '' }}" >> $GITHUB_OUTPUT

      # H-30 SNAPHOT
      - name: H-30 snapshot (meetings + odds)
        if: github.event_name == 'workflow_dispatch' || (github.event_name == 'schedule' && contains('25 15 * * *', github.event.schedule))
        run: |
          mkdir -p data/h30
          python online_fetch_zeturf.py --mode h30 --out data/h30/h30.json
          # Option ciblage R/C si fournis (écrit RnCx-h30.json)
          if [ -n "${{ steps.in.outputs.MEETING }}" ] && [ -n "${{ steps.in.outputs.RACE }}" ]; then
            python pipeline_run.py snapshot --when h30 --meeting "${{ steps.in.outputs.MEETING }}" --race "${{ steps.in.outputs.RACE }}" --outdir data/h30
          fi

      # H-5 ANALYSE + DIFF
      - name: H-5 snapshot + diff + analyse
        if: github.event_name == 'workflow_dispatch' || (github.event_name == 'schedule' && contains('55 15 * * *', github.event.schedule))
        run: |
          mkdir -p data/h5 data/diff data/out
          python online_fetch_zeturf.py --mode h5 --out data/h5/h5.json
          python online_fetch_zeturf.py --mode diff --out data/diff/diff_drift.json
          python pipeline_run.py analyse \
            --h30 data/h30/h30.json \
            --h5  data/h5/h5.json \
            --diff data/diff/diff_drift.json \
            --outdir data/out \
            --allow-je-na=${ALLOW_JE_NA} \
            --budget=${GPI_BUDGET} \
            --ev-global=${EV_MIN_GLOBAL} \
            --roi-global=${ROI_MIN_GLOBAL} \
            --max-vol=${MAX_VOL_PER_HORSE}

      - name: Tests unitaires essentiels
        run: pytest -q

      - name: Upload artefacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gpi_v51_${{ github.run_id }}
          path: |
            data/h30/**
            data/h5/**
            data/diff/**
            data/out/**
