name: Deploy to Cloud Run

on:
  push:
    branches: ["main"]

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: ${{ vars.GCP_PROJECT_ID || secrets.GCP_PROJECT_ID || 'analyse-hippique' }}
      REGION: ${{ vars.GCP_REGION || secrets.GCP_REGION || 'europe-west1' }}
      REPO: ${{ vars.GAR_REPO || secrets.GAR_REPO || 'hippique-analyse' }}
      SERVICE: ${{ vars.SERVICE_NAME || secrets.SERVICE_NAME || 'hippique-analyse' }}      
      # Variables métier (modifiables dans "Repository variables")
      DEFAULT_BUDGET: ${{ vars.DEFAULT_BUDGET || '5.0' }}
      MIN_EV_SP: ${{ vars.MIN_EV_SP || '0.20' }}
      MIN_EV_COMBO: ${{ vars.MIN_EV_COMBO || '0.40' }}
      MAX_VOLAT_PER_HORSE: ${{ vars.MAX_VOLAT_PER_HORSE || '0.60' }}
      DATA_MODE: ${{ vars.DATA_MODE || 'web' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Normalize deployment variables
        shell: bash
        run: |
          set -euo pipefail

          declare -A defaults=(
            [PROJECT_ID]="analyse-hippique"
            [REGION]="europe-west1"
            [REPO]="hippique-analyse"
            [SERVICE]="hippique-analyse"
          )

          for key in PROJECT_ID REGION REPO SERVICE; do
            value="${!key:-}"

            if [[ -z "${value}" ]]; then
              value="${defaults[$key]}"
            fi

            if [[ -z "${value}" ]]; then
              echo "::error::${key} must not be empty after applying defaults."
              exit 1
            fi

            printf -v "${key}" '%s' "${value}"
          done

          IMAGE="${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO}/${SERVICE}:${GITHUB_SHA}"

          if [[ -z "${IMAGE}" ]]; then
            echo "::error::Failed to compute IMAGE value."
            exit 1
          fi

          {
            printf 'REGION=%s\n' "${REGION}"
            printf 'PROJECT_ID=%s\n' "${PROJECT_ID}"
            printf 'REPO=%s\n' "${REPO}"
            printf 'SERVICE=%s\n' "${SERVICE}"
            printf 'IMAGE=%s\n' "${IMAGE}"
          } >> "${GITHUB_ENV}"

      # Auth via clé JSON stockée dans le secret GCP_CREDENTIALS
      - name: Auth to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v3
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Ensure Artifact Registry repo exists
        run: |
          gcloud artifacts repositories create "${REPO}" \
            --repository-format=DOCKER \
            --location="${REGION}" \
            --description="Images hippiques" || true

      - name: Configure Docker to push to Artifact Registry
        run: |
          if [[ -z "${IMAGE}" ]]; then
            echo "::error::IMAGE env var is empty. Please configure the workflow variables (GCP_REGION, GCP_PROJECT_ID, GAR_REPO, SERVICE_NAME)."
            exit 1
          fi
          REGISTRY_HOST="${IMAGE%%/*}"
          if [[ -z "${REGISTRY_HOST}" || "${REGISTRY_HOST}" == "${IMAGE}" || "${REGISTRY_HOST}" == -* ]]; then
            echo "::error::Unable to determine Artifact Registry host from IMAGE='${IMAGE}'."
            exit 1
          fi
          if [[ "${REGISTRY_HOST}" != "${REGION}-docker.pkg.dev" ]]; then
            echo "::error::Artifact Registry host '${REGISTRY_HOST}' does not match expected '${REGION}-docker.pkg.dev'."
            exit 1
          fi
          gcloud auth configure-docker "${REGISTRY_HOST}" --quiet
          
      - name: Build & Push image
        run: |
          docker build -t "${IMAGE}" .
          docker push "${IMAGE}"

      - name: Deploy to Cloud Run        
        run: |
          gcloud run deploy "${SERVICE}" \
            --image "${IMAGE}" \
            --region "${REGION}" \
            --platform managed \
            --allow-unauthenticated \
            --timeout 600 \
            --set-env-vars "DEFAULT_BUDGET=${DEFAULT_BUDGET},MIN_EV_SP=${MIN_EV_SP},MIN_EV_COMBO=${MIN_EV_COMBO},MAX_VOLAT_PER_HORSE=${MAX_VOLAT_PER_HORSE},DATA_MODE=${DATA_MODE}"
          URL="$(gcloud run services describe "${SERVICE}" --region "${REGION}" --format='value(status.url)')"
          echo "Service URL: ${URL}"
            
