name: H5 Exact

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run scheduled H5 analyses
        run: |
          while IFS=';' read -r url dt meeting race; do
            python analyse_courses_du_jour_enrichie.py \
              --reunion-url "$url" \
              --phase H5
          done < schedules.csv
      - name: Sync data to GCS
        run: python scripts/drive_sync.py --push data
        env:
          GCS_SERVICE_KEY_B64: ${{ secrets.GCS_SERVICE_KEY_B64 }}
          GCS_BUCKET: ${{ vars.GCS_BUCKET }}
          GCS_PREFIX: ${{ vars.GCS_PREFIX || '' }}
          GOOGLE_CLOUD_PROJECT: ${{ vars.GOOGLE_CLOUD_PROJECT }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: h5-exact-artifacts
          path: |
            data/**
            prompts/**
          if-no-files-found: warn
