name: 🧪 Test & Validation du Projet

# Déclencheurs
on:
  # Déclenché manuellement depuis l'onglet Actions
  workflow_dispatch:
    inputs:
      test_level:
        description: 'Niveau de test'
        required: true
        default: 'basic'
        type: choice
        options:
          - basic      # Tests de base uniquement
          - full       # Tests complets
          - structure  # Validation structure seulement
      
      run_lint:
        description: 'Lancer le linter sur sources.txt'
        required: false
        type: boolean
        default: true
  
  # Déclenché à chaque push sur main (optionnel)
  push:
    branches:
      - main
    paths:
      - 'scripts/**'
      - 'config/**'
      - 'requirements.txt'
      - '.github/workflows/**'
  
  # Déclenché sur les pull requests
  pull_request:
    branches:
      - main

# Variables d'environnement globales
env:
  PYTHON_VERSION: '3.12'
  TZ: 'Europe/Paris'

jobs:
  # ============================================
  # JOB 1: Validation de la structure
  # ============================================
  validate-structure:
    name: 📁 Valider la structure du projet
    runs-on: ubuntu-latest
    
    steps:
      - name: 📥 Checkout du code
        uses: actions/checkout@v4
      
      - name: 🔍 Vérifier les fichiers critiques
        run: |
          echo "🔍 Vérification des fichiers obligatoires..."
          
          # Liste des fichiers critiques
          CRITICAL_FILES=(
            "sources.txt"
            "requirements.txt"
            ".env.example"
            "config/sources.yml"
            "README.md"
          )
          
          # Liste des dossiers critiques
          CRITICAL_DIRS=(
            "scripts"
            "config"
            "calibration"
            "data"
            "excel"
            ".github/workflows"
          )
          
          MISSING_FILES=()
          MISSING_DIRS=()
          
          # Vérifier les fichiers
          for file in "${CRITICAL_FILES[@]}"; do
            if [ ! -f "$file" ]; then
              echo "❌ Fichier manquant: $file"
              MISSING_FILES+=("$file")
            else
              echo "✅ Trouvé: $file"
            fi
          done
          
          # Vérifier les dossiers
          for dir in "${CRITICAL_DIRS[@]}"; do
            if [ ! -d "$dir" ]; then
              echo "❌ Dossier manquant: $dir"
              MISSING_DIRS+=("$dir")
            else
              echo "✅ Trouvé: $dir/"
            fi
          done
          
          # Rapport final
          if [ ${#MISSING_FILES[@]} -eq 0 ] && [ ${#MISSING_DIRS[@]} -eq 0 ]; then
            echo ""
            echo "✅ Structure du projet valide!"
          else
            echo ""
            echo "❌ Structure du projet invalide!"
            echo "Fichiers manquants: ${#MISSING_FILES[@]}"
            echo "Dossiers manquants: ${#MISSING_DIRS[@]}"
            exit 1
          fi
      
      - name: 🔍 Vérifier sources.txt
        run: |
          echo "🔍 Validation de sources.txt..."
          
          if [ ! -f "sources.txt" ]; then
            echo "❌ sources.txt n'existe pas!"
            exit 1
          fi
          
          # Compter les lignes non vides et non commentées
          URL_COUNT=$(grep -v '^#' sources.txt | grep -v '^$' | wc -l)
          
          echo "📊 Nombre d'URLs trouvées: $URL_COUNT"
          
          if [ $URL_COUNT -eq 0 ]; then
            echo "⚠️ Attention: sources.txt est vide ou ne contient que des commentaires"
            echo "   Ajoutez des URLs ZEturf pour les tests"
          else
            echo "✅ sources.txt contient $URL_COUNT URL(s)"
            echo ""
            echo "URLs trouvées:"
            grep -v '^#' sources.txt | grep -v '^$' | head -5
          fi
      
      - name: 📊 Résumé de la structure
        run: |
          echo "📊 RÉSUMÉ DE LA STRUCTURE"
          echo "========================="
          echo ""
          tree -L 2 -I '__pycache__|*.pyc|venv|.git' || ls -R

  # ============================================
  # JOB 2: Installation et dépendances
  # ============================================
  test-installation:
    name: 🔧 Tester l'installation
    runs-on: ubuntu-latest
    needs: validate-structure
    
    steps:
      - name: 📥 Checkout du code
        uses: actions/checkout@v4
      
      - name: 🐍 Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
      
      - name: 📦 Mettre à jour pip
        run: |
          python -m pip install --upgrade pip setuptools wheel
      
      - name: 📦 Installer les dépendances
        run: |
          echo "📦 Installation des dépendances depuis requirements.txt..."
          
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
            echo "✅ Dépendances installées"
          else
            echo "❌ requirements.txt introuvable!"
            exit 1
          fi
      
      - name: 🔍 Vérifier les imports critiques
        run: |
          echo "🔍 Test des imports Python..."
          
          python << 'EOF'
          import sys
          
          critical_imports = [
              'pandas',
              'numpy',
              'requests',
              'yaml',
              'bs4',
              'openpyxl',
              'google.cloud.storage'
          ]
          
          failed = []
          
          for module in critical_imports:
              try:
                  __import__(module)
                  print(f"✅ {module}")
              except ImportError as e:
                  print(f"❌ {module}: {e}")
                  failed.append(module)
          
          if failed:
              print(f"\n❌ {len(failed)} module(s) manquant(s): {', '.join(failed)}")
              sys.exit(1)
          else:
              print("\n✅ Tous les imports critiques fonctionnent!")
          EOF
      
      - name: 📊 Versions des packages
        run: |
          echo "📊 Versions installées:"
          pip list | grep -E "(pandas|numpy|requests|google-cloud-storage|fastapi|openpyxl|pyyaml|beautifulsoup4)"

  # ============================================
  # JOB 3: Validation des configurations
  # ============================================
  validate-configs:
    name: ⚙️ Valider les configurations
    runs-on: ubuntu-latest
    needs: validate-structure
    
    steps:
      - name: 📥 Checkout du code
        uses: actions/checkout@v4
      
      - name: 🐍 Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: 📦 Installer PyYAML
        run: pip install pyyaml
      
      - name: 🔍 Valider config/sources.yml
        run: |
          echo "🔍 Validation de config/sources.yml..."
          
          python << 'EOF'
          import yaml
          import sys
          
          try:
              with open('config/sources.yml', 'r') as f:
                  config = yaml.safe_load(f)
              
              # Vérifier la structure
              if 'zeturf' not in config:
                  print("❌ Clé 'zeturf' manquante dans sources.yml")
                  sys.exit(1)
              
              if 'url' not in config['zeturf']:
                  print("❌ Clé 'url' manquante dans sources.yml['zeturf']")
                  sys.exit(1)
              
              url = config['zeturf']['url']
              
              if '{course_id}' not in url:
                  print("⚠️ Placeholder {course_id} absent dans l'URL")
              
              print("✅ config/sources.yml est valide")
              print(f"   URL template: {url}")
              
          except FileNotFoundError:
              print("❌ config/sources.yml introuvable!")
              sys.exit(1)
          except yaml.YAMLError as e:
              print(f"❌ Erreur YAML: {e}")
              sys.exit(1)
          EOF
      
      - name: 🔍 Valider .env.example
        run: |
          echo "🔍 Validation de .env.example..."
          
          if [ ! -f ".env.example" ]; then
            echo "❌ .env.example introuvable!"
            exit 1
          fi
          
          # Variables obligatoires à vérifier
          REQUIRED_VARS=(
            "GCS_BUCKET"
            "GCS_SERVICE_KEY_B64"
            "ZETURF_LOGIN"
            "ZETURF_PASSWORD"
          )
          
          MISSING_VARS=()
          
          for var in "${REQUIRED_VARS[@]}"; do
            if ! grep -q "^$var=" .env.example; then
              echo "❌ Variable manquante: $var"
              MISSING_VARS+=("$var")
            else
              echo "✅ Variable trouvée: $var"
            fi
          done
          
          if [ ${#MISSING_VARS[@]} -eq 0 ]; then
            echo "✅ .env.example contient toutes les variables obligatoires"
          else
            echo "❌ Variables manquantes: ${MISSING_VARS[@]}"
            exit 1
          fi

  # ============================================
  # JOB 4: Linter sources.txt
  # ============================================
  lint-sources:
    name: 🔍 Lint sources.txt
    runs-on: ubuntu-latest
    needs: test-installation
    if: ${{ github.event.inputs.run_lint != 'false' }}
    
    steps:
      - name: 📥 Checkout du code
        uses: actions/checkout@v4
      
      - name: 🐍 Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: 📦 Installer dépendances
        run: |
          pip install requests validators pyyaml
      
      - name: 🔍 Linter sources.txt
        run: |
          if [ -f "scripts/lint_sources.py" ]; then
            echo "🔍 Exécution du linter..."
            python scripts/lint_sources.py --file sources.txt --warn-only
          else
            echo "⚠️ scripts/lint_sources.py non trouvé, création d'un linter basique..."
            
            python << 'EOF'
          import re
          import sys
          
          def validate_sources():
              errors = []
              warnings = []
              
              with open('sources.txt', 'r') as f:
                  lines = f.readlines()
              
              urls = []
              for i, line in enumerate(lines, 1):
                  line = line.strip()
                  
                  # Ignorer commentaires et lignes vides
                  if not line or line.startswith('#'):
                      continue
                  
                  # Vérifier format URL
                  if not line.startswith('https://www.zeturf.fr/'):
                      errors.append(f"Ligne {i}: URL invalide (doit commencer par https://www.zeturf.fr/)")
                  
                  # Vérifier doublons
                  if line in urls:
                      warnings.append(f"Ligne {i}: URL dupliquée: {line}")
                  
                  urls.append(line)
              
              # Rapport
              print(f"📊 {len(urls)} URL(s) trouvée(s)")
              
              if warnings:
                  print(f"\n⚠️ {len(warnings)} avertissement(s):")
                  for w in warnings:
                      print(f"  {w}")
              
              if errors:
                  print(f"\n❌ {len(errors)} erreur(s):")
                  for e in errors:
                      print(f"  {e}")
                  return False
              
              print("\n✅ sources.txt est valide!")
              return True
          
          if not validate_sources():
              sys.exit(1)
          EOF
          fi

  # ============================================
  # JOB 5: Tests unitaires basiques
  # ============================================
  basic-tests:
    name: 🧪 Tests basiques
    runs-on: ubuntu-latest
    needs: test-installation
    if: ${{ github.event.inputs.test_level != 'structure' }}
    
    steps:
      - name: 📥 Checkout du code
        uses: actions/checkout@v4
      
      - name: 🐍 Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: 📦 Installer dépendances
        run: |
          pip install -r requirements.txt
      
      - name: 🧪 Test imports des scripts
        run: |
          echo "🧪 Test des imports des scripts..."
          
          for script in scripts/*.py; do
            if [ -f "$script" ]; then
              echo "Vérification: $script"
              python -m py_compile "$script" && echo "  ✅ $script" || echo "  ❌ $script"
            fi
          done
      
      - name: 🧪 Test syntaxe Python
        run: |
          echo "🧪 Vérification syntaxe Python de tous les fichiers..."
          find . -name "*.py" -not -path "./venv/*" -not -path "./.git/*" | while read file; do
            python -m py_compile "$file" && echo "✅ $file" || (echo "❌ $file" && exit 1)
          done

  # ============================================
  # JOB 6: Résumé final
  # ============================================
  test-summary:
    name: 📊 Résumé des tests
    runs-on: ubuntu-latest
    needs: [validate-structure, test-installation, validate-configs, basic-tests]
    if: always()
    
    steps:
      - name: 📊 Générer le résumé
        run: |
          echo "# 📊 RÉSUMÉ DES TESTS" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Job | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|-----|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| Structure | ${{ needs.validate-structure.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Installation | ${{ needs.test-installation.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Configuration | ${{ needs.validate-configs.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Tests basiques | ${{ needs.basic-tests.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          if [ "${{ needs.validate-structure.result }}" == "success" ] && \
             [ "${{ needs.test-installation.result }}" == "success" ] && \
             [ "${{ needs.validate-configs.result }}" == "success" ]; then
            echo "## ✅ Tous les tests critiques ont réussi!" >> $GITHUB_STEP_SUMMARY
          else
            echo "## ❌ Certains tests ont échoué" >> $GITHUB_STEP_SUMMARY
          fi
