name: Result Exact

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

env:
  TZ: Europe/Paris
  PYTHONUNBUFFERED: "1"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run result window (T+14 to T+16)
        run: |
          python runner_chain.py --phase RESULT --result-window-min 14 --result-window-max 16
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: result-exact-artifacts
          path: |
            data/**
            excel/modele_suivi_courses_hippiques.xlsx
          if-no-files-found: warn
