BUDGET_TOTAL: 5
SP_RATIO: 0.6
COMBO_RATIO: 0.4
EV_MIN_SP: 0.20
EV_MIN_GLOBAL: 0.40
ROI_MIN_SP: 0.20
ROI_MIN_GLOBAL: 0.40
ROR_MAX: 0.05
SHARPE_MIN: 0.0
MAX_VOL_PAR_CHEVAL: 0.60
ALLOW_JE_NA: false
PAUSE_EXOTIQUES: false
OUTDIR_DEFAULT: "runs/latest"
EXCEL_PATH: "modele_suivi_courses_hippiques.xlsx"
CALIB_PATH: "payout_calibration.yaml"
MODEL: "GPI v5.1"
REQUIRE_DRIFT_LOG: true
REQUIRE_ODDS_WINDOWS:
  - 30
  - 5
MIN_PAYOUT_COMBOS: 10.0
MAX_TICKETS_SP: 1
MIN_STAKE_SP: 0.10
DRIFT_COEF: 0.05
ROUND_TO_SP: 0.10
JE_BONUS_COEF: 0.001
