BUDGET_TOTAL: 5
SP_RATIO: 0.6
COMBO_RATIO: 0.4
EV_MIN_SP: 0.15
EV_MIN_SP_HOMOGENEOUS: 0.10
EV_MIN_GLOBAL: 0.35
ROI_MIN_SP: 0.10
ROI_MIN_GLOBAL: 0.25
ROR_MAX: 0.05
MIN_PAYOUT_COMBOS: 12.0
SHARPE_MIN: 0.5
MAX_VOL_PAR_CHEVAL: 0.60
ALLOW_JE_NA: false
PAUSE_EXOTIQUES: false
OUTDIR_DEFAULT: "runs/latest"
EXCEL_PATH: "modele_suivi_courses_hippiques.xlsx"
CALIB_PATH: "payout_calibration.yaml"
MODEL: "GPI v5.1"
REQUIRE_DRIFT_LOG: true
REQUIRE_ODDS_WINDOWS:
  - 30
  - 5
MAX_TICKETS_SP: 1
MIN_STAKE_SP: 0.10
DRIFT_COEF: 0.05
ROUND_TO_SP: 0.10
JE_BONUS_COEF: 0.001
