pmu:
  url: "https://offline.turfinfo.api.pmu.fr/rest/client/7/programme/{date}/{reunion}/{course}"
zeturf:
  url: "https://m.zeeturf.fr/rest/api/2/race/{course_id}"
geny:
  url: "https://www.geny.com/reunions-courses-pmu"
