name: Planning ZEturf Fetch

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'  # 06:00 CET

jobs:
  planning:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Paris
      PYTHONUNBUFFERED: '1'
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Ensure scripts package
        run: |
          mkdir -p scripts
          [ -f scripts/__init__.py ] || touch scripts/__init__.py

      - name: Run planning fetch
        env:
          PYTHONPATH: .
        run: |
          python online_fetch_zeturf.py \
            --mode planning \
            --out data/planning/$(date +%F).json \
            --sources config/sources.yml
            
      - name: Commit planning
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git pull --rebase origin main
          git add data/planning/*.json
          git commit -m "planning: $(date +%F)" || echo "No changes"
          git push
      - name: Sync data to GCS
        run: python scripts/drive_sync.py --push data
        env:
          GCS_SERVICE_KEY_B64: ${{ secrets.GCS_SERVICE_KEY_B64 }}
          GCS_BUCKET: ${{ vars.GCS_BUCKET }}
          GCS_PREFIX: ${{ vars.GCS_PREFIX || '' }}
          GOOGLE_CLOUD_PROJECT: ${{ vars.GOOGLE_CLOUD_PROJECT }}
