name: GPI v5.1 - Daily Planning

on:
  schedule:
    - cron: "0 6 * * *"  # 06:00 UTC = 08:00 Europe/Paris (été)
    - cron: "0 7 * * *"  # 07:00 UTC = 08:00 Europe/Paris (hiver)
  workflow_dispatch: {}

env:
  TZ: Europe/Paris
  PYTHONUNBUFFERED: "1"

jobs:
  planning:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Generate today's planning (meetings + races + hours)
        run: |
          python scripts/online_fetch_zeturf.py \
            --mode planning \
            --out data/planning/$(date +%F).json \
            --sources config/sources.yml
      - name: Commit planning
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add data/planning/*.json
          git commit -m "planning: $(date +%F)" || echo "No changes"
          git push
