name: Deploy Cloud Run Job

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Optional image tag override"
        required: false
        default: ""

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      REGION: ${{ secrets.GCP_REGION }}
      JOB_NAME: ${{ secrets.CLOUD_RUN_JOB_NAME }}
      SCHEDULER_NAME: ${{ secrets.CLOUD_RUN_SCHEDULER_NAME }}
      SCHEDULE: ${{ secrets.CLOUD_RUN_SCHEDULE }}
      REPOSITORY: ${{ secrets.ARTIFACT_REPO }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          token_format: "access_token"
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Set up gcloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure Artifact Registry auth
        run: |
          gcloud auth configure-docker "${REGION}-docker.pkg.dev" --quiet

      - name: Build and push container image
        run: |
          IMAGE_TAG="${{ github.sha }}"
          if [ -n "${{ github.event.inputs.image_tag }}" ]; then
            IMAGE_TAG="${{ github.event.inputs.image_tag }}"
          fi
          IMAGE_URI="${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/hippique-analyse:${IMAGE_TAG}"
          gcloud builds submit --tag "$IMAGE_URI" .
          echo "image_uri=$IMAGE_URI" >> "$GITHUB_OUTPUT"
        id: build

      - name: Deploy Cloud Run Job
        run: |
          IMAGE_URI="${{ steps.build.outputs.image_uri }}"
          gcloud run jobs deploy "$JOB_NAME" \
            --image "$IMAGE_URI" \
            --region "$REGION" \
            --project "$PROJECT_ID" \
            --max-retries=1 \
            --memory=2Gi \
            --set-env-vars PIPELINE_MODE=hminus5,OUTPUT_DIR=/app/out

      - name: Ensure Cloud Scheduler trigger
        run: |
          set -euo pipefail
          BASE_URL="https://${REGION}-run.googleapis.com/apis/run.googleapis.com/v1/namespaces/${PROJECT_ID}/jobs/${JOB_NAME}:run"
          if ! gcloud scheduler jobs describe "$SCHEDULER_NAME" --location "$REGION" --project "$PROJECT_ID" >/dev/null 2>&1; then
            gcloud scheduler jobs create http "$SCHEDULER_NAME" \
              --project "$PROJECT_ID" \
              --location "$REGION" \
              --schedule "$SCHEDULE" \
              --uri "$BASE_URL" \
              --http-method POST \
              --oidc-service-account-email "${{ secrets.GCP_SERVICE_ACCOUNT }}"
          fi
          gcloud scheduler jobs update http "$SCHEDULER_NAME" \
            --project "$PROJECT_ID" \
            --location "$REGION" \
            --schedule "$SCHEDULE" \
            --uri "$BASE_URL" \
            --http-method POST \
            --oidc-service-account-email "${{ secrets.GCP_SERVICE_ACCOUNT }}"

      - name: Show job state
        run: |
          gcloud run jobs describe "$JOB_NAME" --region "$REGION" --project "$PROJECT_ID"
          gcloud scheduler jobs describe "$SCHEDULER_NAME" --location "$REGION" --project "$PROJECT_ID"
