name: Deploy Cloud Run

on:
  workflow_dispatch:
    inputs:
      service: { description: "Cloud Run service name", required: true }
      region:  { description: "GCP region (europe-west1...)", required: true }
      project_id: { description: "GCP Project ID", required: true }
      source_dir: { description: "Build dir", required: false, default: "." }

permissions:
  contents: read
  id-token: write

concurrency:
  group: deploy-cloudrun-${{ github.run_id }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_DEPLOY_SA }}
          token_format: access_token
      - uses: google-github-actions/setup-gcloud@v2
        with: { project_id: ${{ inputs.project_id }} }
      - name: Configure AR
        run: gcloud auth configure-docker "${{ inputs.region }}-docker.pkg.dev" -q
      - name: Build & Push
        run: |
          IMG="${{ inputs.region }}-docker.pkg.dev/${{ inputs.project_id }}/hippiq-repo/${{ inputs.service }}:${{ github.sha }}"
          gcloud builds submit ${{ inputs.source_dir }} --tag "$IMG"
          echo "IMAGE=$IMG" >> $GITHUB_ENV
      - name: Deploy
        run: |
          gcloud run deploy ${{ inputs.service }} --image "$IMAGE" --region ${{ inputs.region }} \
            --platform managed --allow-unauthenticated --max-instances 2 --timeout 900 --memory 512Mi
