name: GPI v5.1 - GPI

on:
  workflow_dispatch:
    inputs:
      course_id:
        description: "Course ID"
        required: true
  schedule:
    - cron: "25 15 * * *"
    - cron: "55 15 * * *"

permissions:
  contents: read
  
env:
  TZ: Europe/Paris

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Inject course ID into source URL
        if: github.event_name == 'workflow_dispatch'
        run: |
          cid="${{ github.event.inputs.course_id }}"
          test -n "$cid"
          sed -i "s/{course_id}/$cid/" config/sources.yml
      - name: Fetch H-30 odds
        if: github.event_name == 'schedule' && github.event.schedule == '25 15 * * *'
        run: |
          python online_fetch_zeturf.py --mode h30 --out data/h30.json
      - name: Fetch H-5 odds
        if: github.event_name == 'workflow_dispatch' || (github.event_name == 'schedule' && github.event.schedule == '55 15 * * *')
        run: python online_fetch_zeturf.py --mode h5 --out data/h5.json
      - name: Compute diff
        if: github.event_name == 'workflow_dispatch' || (github.event_name == 'schedule' && github.event.schedule == '55 15 * * *')
        run: python online_fetch_zeturf.py --mode diff --out data/diff.json
      - name: Run tests
        if: github.event_name == 'workflow_dispatch' || (github.event_name == 'schedule' && github.event.schedule == '55 15 * * *')
        run: pytest -q
      - name: Run pipeline
        if: github.event_name == 'workflow_dispatch' || (github.event_name == 'schedule' && github.event.schedule == '55 15 * * *')
        run: |
          python pipeline_run.py
      - name: Sync data to Drive
        run: python scripts/drive_sync.py --push data
        env:
          GOOGLE_CREDENTIALS_B64: ${{ secrets.GOOGLE_CREDENTIALS_B64 }}
          DRIVE_FOLDER_ID: ${{ secrets.DRIVE_FOLDER_ID }}
