name: Hippique Cron

on:
  schedule:
    - cron: "*/5 * * * *"
    - cron: "0 8 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  prepare:
      if: github.event.schedule == '0 8 * * *'
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v5
        - uses: actions/setup-python@v6
          with:
            python-version: "3.11"
        - run: pip install -r requirements.txt
        - run: |
            python scripts/online_fetch_zeturf.py --mode planning --out meetings.json --sources config/sources.yml
        - name: Sync data to GCS
          run: python scripts/drive_sync.py --push data
          env:
            GCS_SERVICE_KEY_B64: ${{ secrets.GCS_SERVICE_KEY_B64 }}
            GCS_BUCKET: ${{ vars.GCS_BUCKET }}
            GCS_PREFIX: ${{ vars.GCS_PREFIX || '' }}
            GOOGLE_CLOUD_PROJECT: ${{ vars.GOOGLE_CLOUD_PROJECT }}
        - uses: actions/upload-artifact@v4
          with:
            name: meetings
            path: meetings.json
  cron:
    if: github.event.schedule != '0 8 * * *'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: |
          if [ ! -f meetings.json ]; then
            python scripts/online_fetch_zeturf.py --mode planning --out meetings.json --sources config/sources.yml
          fi
          python scripts/cron_decider.py --meetings meetings.json
      - name: Sync data to GCS
        run: python scripts/drive_sync.py --push data
        env:
          GCS_SERVICE_KEY_B64: ${{ secrets.GCS_SERVICE_KEY_B64 }}
          GCS_BUCKET: ${{ vars.GCS_BUCKET }}
          GCS_PREFIX: ${{ vars.GCS_PREFIX || '' }}
          GOOGLE_CLOUD_PROJECT: ${{ vars.GOOGLE_CLOUD_PROJECT }}
      - uses: actions/upload-artifact@v4
        with:
          name: cron-data
          path: |
            meetings.json
            data
