name: GPI v5.1 - Post Results

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch: {}

env:
  TZ: Europe/Paris
  PYTHONUNBUFFERED: "1"

jobs:
  results:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Fetch results + prepare Excel update commands
        run: |
         python scripts/get_arrivee_geny.py \
            --planning data/planning/$(date +%F).json \
            --out data/results/$(date +%F)_arrivees.json
            
          python scripts/p_finale_export.py \
            --arrivees data/results/$(date +%F)_arrivees.json \
            --analyses-dir data/analyses \
            --excel excel/modele_suivi_courses_hippiques.xlsx \
            --out-dir data/results

      - name: Update Excel with results
        run: |
          python scripts/update_excel_with_results.py \
            --excel excel/modele_suivi_courses_hippiques.xlsx \
            --arrivees data/results/$(date +%F)_arrivees.json \
            --analyses-dir data/analyses \
            --results-dir data/results \
            --save

      - name: Commit results + updated Excel
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add data/results/** excel/*.xlsx
          git commit -m "results+excel: $(date +%F' '%T)" || echo "No changes"
          git push

      - name: Upload results + Excel to Drive
        env:
          DRIVE_FOLDER_ID: ${{ secrets.DRIVE_FOLDER_ID }}
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
        run: |
          python scripts/drive_sync.py \            
            --upload-glob "data/results/**/*.json" \
            --upload-glob "excel/*.xlsx"
