name: GPI v5.1 - Scheduler (H-30 / H-5)

on:
  workflow_dispatch:
    inputs:
      mode:
        description: "Phase à déclencher (h30 ou h5)"
        required: true
        default: "h5"
      course_id:
        description: "Identifiant numérique de la course"
        required: true
      date:
        description: "Date de la réunion (YYYY-MM-DD)"
        required: true
      meeting:
        description: "Identifiant réunion (ex: R1)"
        required: true
      race:
        description: "Identifiant course (ex: C3)"
        required: true
      hippodrome:
        description: "Hippodrome concerné"
        required: false
        default: ""
      discipline:
        description: "Discipline (plat, trot, obstacle)"
        required: false
        default: ""
  schedule:
    - cron: "*/10 7-21 * * *"

concurrency:
  group: hminus-${{ github.event.inputs.course_id || github.run_id }}
  cancel-in-progress: false

permissions:
  contents: write

env:
  PYTHONUTF8: "1"
  TZ: Europe/Paris
  USE_GCS: "false"
  OUTPUT_DIR: out/hminus
  GPI_BUDGET: ${{ vars.SCHEDULER_GPI_BUDGET || '5' }}
  EV_MIN: ${{ vars.SCHEDULER_EV_MIN || '0.35' }}
  ROI_MIN: ${{ vars.SCHEDULER_ROI_MIN || '0.25' }}
  PASTILLE_RULE: ${{ vars.SCHEDULER_PASTILLE_RULE || '' }}

jobs:
  schedule-runner:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scheduler windows (H-30/H-5)
        run: |
          mkdir -p "${OUTPUT_DIR}/analyses"
          python scripts/runner_chain.py \
            --planning "data/planning/$(date +%F).json" \
            --h30-window-min 27 --h30-window-max 33 \
            --h5-window-min 3 --h5-window-max 7 \
            --snap-dir data/snapshots \
            --analysis-dir "${OUTPUT_DIR}/analyses" \
            --output "${OUTPUT_DIR}/analyses" \
            --budget "${GPI_BUDGET}" \
            --ev-min "${EV_MIN}" \
            --roi-min "${ROI_MIN}" \
            --pastille-rule "${PASTILLE_RULE}" \
            --gpi-config config/gpi_v51.yml

      - name: Export normalized JSON/CSV
        run: |
          set -euo pipefail
          mkdir -p "${OUTPUT_DIR}"
          
          analysis_root="${OUTPUT_DIR}/analyses"
          mkdir -p "${analysis_root}"
          found=0

          while IFS= read -r pfinale; do
            [ -n "${pfinale}" ] || continue
            if [ ! -f "${pfinale}" ]; then
              continue
            fi
            dir=$(dirname "${pfinale}")
            echo "[export] Traitement de ${dir}"
            python "${GITHUB_WORKSPACE}/p_finale_export.py" \
              --outputs-dir "${dir}"
            found=1
          done < <(find "${analysis_root}" -type f -name 'p_finale.json' 2>/dev/null || true)

          if [ "${found}" -eq 0 ]; then
            echo "[WARN] Aucun p_finale.json détecté sous ${analysis_root}" >&2
          fi


      - name: Upload artifacts (H-30/H-5)
        uses: actions/upload-artifact@v4
        with:
          name: hminus-${{ github.run_id }}
          path: |
            out/hminus/**
            data/snapshots/**
            !**/__pycache__/**

      - name: Commit results to data branch
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: EndBug/add-and-commit@v9
        with:
          add: |
            out/hminus
            data/snapshots
          message: "Scheduler H-30/H-5: export sans Drive (${{ github.run_id }})"
          new_branch: data-hminus
          push: true
