name: GPI v5.1 - Scheduler (H-30 / H-5)

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch: {}

env:
  TZ: Europe/Paris
  PYTHONUNBUFFERED: "1"
  GPI_BUDGET: "5"
  EV_MIN: "0.40"     # +40% requis
  ROI_MIN: "0.20"    # +20% requis
  PASTILLE_RULE: "ev>=0.40 && roi>=0.20 && payout_min>=10"

jobs:
  schedule-runner:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v6
        with: { python-version: "3.12" }
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run scheduler windows (H-30/H-5)
        run: |
          python scripts/runner_chain.py \
            --planning data/planning/$(date +%F).json \
            --h30-window-min 27 --h30-window-max 33 \
            --h5-window-min 3 --h5-window-max 7 \
            --snap-dir data/snapshots \
            --analysis-dir data/analyses \
            --budget ${GPI_BUDGET} \
            --ev-min ${EV_MIN} \
            --roi-min ${ROI_MIN} \
            --pastille-rule "${PASTILLE_RULE}" \
            --gpi-config config/gpi_v51.yml \
            --payout-calib config/payout_calibration.yaml
      - name: Commit snapshots/analyses
        run: |
          mkdir -p data/snapshots data/analyses
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git pull --rebase origin main
          PREV_SHA=$(git rev-parse HEAD)
          echo "PREV_SHA=$PREV_SHA" >> $GITHUB_ENV
          git add -A data/snapshots data/analyses
          git diff --cached --quiet || git commit -m "snap/analysis: $(date +%F' '%T)"
          git push
          
      - name: Upload to Drive (if any new files)
        env:
          DRIVE_FOLDER_ID: ${{ secrets.DRIVE_FOLDER_ID }}
          GOOGLE_CREDENTIALS_B64: ${{ secrets.GOOGLE_CREDENTIALS_B64 }}
        run: |
          if [ -n "$(git diff --name-only $PREV_SHA HEAD | grep '^data/')" ]; then
            python scripts/drive_sync.py \
              --folder-id "${DRIVE_FOLDER_ID}" \              
              --upload-glob "data/analyses/**/*.json" \
              --upload-glob "data/snapshots/**/*.json"
            fi

      - name: Sync data to Drive
        run: python scripts/drive_sync.py --push data
        env:
          GOOGLE_CREDENTIALS_B64: ${{ secrets.GOOGLE_CREDENTIALS_B64 }}
          DRIVE_FOLDER_ID: ${{ secrets.DRIVE_FOLDER_ID }}
