name: Python tests (GPI v5.1)

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests
        run: pytest -q

      - name: No Drive sync (no credentials)
        if: ${{ !secrets.GOOGLE_CREDENTIALS_B64 }}
        run: echo "Skipping Drive sync because GOOGLE_CREDENTIALS_B64 is not set."

      - name: Sync data to Drive
        if: ${{ secrets.GOOGLE_CREDENTIALS_B64 }}
        run: python drive_sync.py --push data
        env:
          GOOGLE_CREDENTIALS_B64: ${{ secrets.GOOGLE_CREDENTIALS_B64 }}
          DRIVE_FOLDER_ID: ${{ secrets.DRIVE_FOLDER_ID }}
