name: Python tests (GPI v5.1)

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GOOGLE_CREDENTIALS_B64: ${{ secrets.GOOGLE_CREDENTIALS_B64 || '' }}
      DRIVE_FOLDER_ID: ${{ secrets.DRIVE_FOLDER_ID || '' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install deps
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests
        run: pytest -q

      - name: Skip Drive sync (missing credentials)
        if: ${{ env.GOOGLE_CREDENTIALS_B64 == '' }}
        run: echo "Skipping Drive sync because GOOGLE_CREDENTIALS_B64 secret is not available (e.g., PR from fork)."

      - name: Sync data to Drive
        if: ${{ env.GOOGLE_CREDENTIALS_B64 != '' }}
        run: |
          echo "$GOOGLE_CREDENTIALS_B64" | base64 -d > credentials.json
          python drive_sync.py --push data
