name: Python tests (GPI v5.1)

permissions:
  contents: read
  
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GCS_SERVICE_KEY_B64: ${{ secrets.GCS_SERVICE_KEY_B64 }}
      GCS_BUCKET: ${{ vars.GCS_BUCKET }}
      GCS_PREFIX: ${{ vars.GCS_PREFIX || '' }}
      GOOGLE_CLOUD_PROJECT: ${{ vars.GOOGLE_CLOUD_PROJECT }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt
      - run: pytest -q
      - name: Skip GCS sync (missing credentials)
        if: ${{ env.GCS_SERVICE_KEY_B64 == '' }}
        run: echo "Skipping GCS sync because GCS_SERVICE_KEY_B64 secret is not available."
      - name: Sync data to GCS
        if: ${{ env.GCS_SERVICE_KEY_B64 != '' }}
        run: python scripts/drive_sync.py --push data
        

